# Generated by Django 5.0.6 on 2024-05-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(default='dakd', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(default='city', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='cnic',
            field=models.IntegerField(default=232),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.CharField(default='akdl', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='skdj', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.IntegerField(default=232),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='postel_code',
            field=models.IntegerField(default=232),
            preserve_default=False,
        ),
    ]
