# Generated by Django 5.0.6 on 2024-05-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_account_address_account_city_account_cnic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.CharField(default='skdl', max_length=50),
            preserve_default=False,
        ),
    ]
