# Generated by Django 5.0.6 on 2024-05-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_account_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default='sldk', max_length=50),
            preserve_default=False,
        ),
    ]
