# Generated by Django 5.0.6 on 2024-05-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_account_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recieve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='send',
            field=models.BooleanField(default=False),
        ),
    ]
