# Generated by Django 5.0.6 on 2024-06-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_account_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='recieve',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='send',
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('send', 'Send'), ('receive', 'Receive'), ('deposit', 'Deposit'), ('withdraw', 'Withdraw')], default='none', max_length=10),
        ),
    ]
