# Generated by Django 5.0.6 on 2024-06-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_transaction_recieve_remove_transaction_send_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
    ]
