# Generated by Django 5.0.6 on 2024-06-06 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_account_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
    ]
